### ISSUE TITLE
error mkdir file exists when decompressing the zip file in Windows

### ISSUE THREAD

**Issue by grj001** [node-modules/compressing#105]
When decompressing the zip file in Windows, an error occurred and I changed here

mkdir file exists

lib/zip/uncompress_stream.js

```js
const type = /[\\\/]$/.test(entry.fileName) ? 'directory' : 'file';
```

**Comment by fengmk2** [comment]
Can you send a pull request to fix this?

**Comment by fengmk2** [comment]
@grj001 Thanks a lot!
