### ISSUE TITLE
windows tgz and linux tar zxvf, path error

### ISSUE THREAD

**Issue by xinggangling** [node-modules/compressing#22]
###
compressing.tgz....a dir which contain dir\a.js, dir\b.js; then upload this tgz to linux, and run tar zxvf xx.tgz, the result is unexpected( dir\a.js , dir\b.js ); 

####
I think the problem is not change /\\/ to / on windows; the path is at lib/tar/stream.js/_addDirEntry();
I modify like below and works well: 
```
_addDirEntry(entry, opts) {
    fs.readdir(entry, (err, files) => {
      if (err) return this.emit('error', err);

      const relativePath = opts.relativePath || '';
      files.forEach(fileOrDir => {
        const newOpts = utils.clone(opts);
        if (opts.ignoreBase) {
          newOpts.relativePath = path.join(relativePath, fileOrDir).replace(/\\/g, '/');
        } else {
          newOpts.relativePath = path.join(relativePath, path.basename(entry), fileOrDir).replace(/\\/g, '/');
        }
        newOpts.ignoreBase = true;
        this.addEntry(path.join(entry, fileOrDir).replace(/\\/g, '/'), newOpts);
      });
      this._onEntryFinish();
    });
  }
```

####
I do not whether this is a good idea, or I can fix it by so config; if not; I hope this problem can fixed as soon as posibble; best wishes to you ^ _ ^

**Comment by fengmk2** [comment]
can you upload the demo tgz file here? we can fix it or you can help us fix it .

**Comment by xinggangling** [comment]
[demo.zip](https://github.com/node-modules/compressing/files/2732216/demo.zip)

###this zip contain a tgz file which is used compressing.tgz compress; you can try run zxvf dist.201901071743.tgz on linux, You can find the path is not expected.

![1546855114 1](https://user-images.githubusercontent.com/18533687/50761620-d3926000-12a5-11e9-857b-7669849141b9.jpg)

**Comment by FatDong1** [comment]
same issue

**Comment by hejxing** [comment]
+1

**Comment by frankggyy** [comment]
same issue

**Comment by binperson** [comment]
https://www.npmjs.com/package/@01js/compressing
