### ISSUE TITLE
解压中文文件名的时候，出现乱码

### ISSUE THREAD

**Issue by minikiller** [node-modules/compressing#23]
代码如下：
```
compress() {
                const compressing = require('compressing');
                // 解压缩
                compressing.zip.uncompress('build.zip', 'nodejs-compressing-demo3')
                    .then(() => {
                        console.log('success');
                    })
                    .catch(err => {
                        console.error(err);
                    });
            },
```
测试zip文件中包含有中文文件名的文件时候，解压出来的文件名是乱码。

**Comment by HiKWang** [comment]
同问

**Comment by justquanyin** [comment]
+1

**Comment by fengmk2** [comment]
如果你压缩之前的文件名不是 utf8 的，那么解压出来就会乱码。估计还得增加一个编码参数才行。

**Comment by helloyoucan** [comment]
+1

**Comment by helloyoucan** [comment]
同问

**Comment by zhipenglin** [comment]
加个参数大概就好了，可以试试。找了一上午，看了源码才发现，这个包是支持传字符集参数的
`
compress() {
                const compressing = require('compressing');
                // 解压缩
                compressing.zip.uncompress('build.zip', 'nodejs-compressing-demo3',{
zipFileNameEncoding:'GBK'
})
                    .then(() => {
                        console.log('success');
                    })
                    .catch(err => {
                        console.error(err);
                    });
            },
`

**Comment by InCodingNowLiu** [comment]
线上打包出来，这个字符集参数不起作用，本地dev启动是好的，线上走prod的webpack打包出来是有问题的，有遇到这种情况的小伙伴么

**Comment by mxlt02** [comment]
> 加个参数大概就好了，可以试试。找了一上午，看了源码才发现，这个包是支持传字符集参数的
> 
> ```js
> compress() {
>                 const compressing = require('compressing');
>                 // 解压缩
>                 compressing.zip.uncompress('build.zip', 'nodejs-compressing-demo3',{
> zipFileNameEncoding:'GBK'
> })
>                     .then(() => {
>                         console.log('success');
>                     })
>                     .catch(err => {
>                         console.error(err);
>                     });
>             },
> ```

有效!

**Comment by fengmk2** [comment]
不知道 zip 的 entry 是否有字符编码信息，如果有就可以自动探测编码解决 https://github.com/node-modules/compressing/blob/ff9178c51ff0f2e75ac0b31cc661cf43bc657035/lib/zip/uncompress_stream.js#L88

**Comment by fengmk2** [comment]
有人可以提供一个有问题的 zip 测试文件么，这样我可以作为测试用例，尝试解决一下。

**Comment by mxlt02** [comment]
> 有人可以提供一个有问题的 zip 测试文件么，这样我可以作为测试用例，尝试解决一下。

[configs.zip](https://github.com/node-modules/compressing/files/12414467/configs.zip)
![image](https://github.com/node-modules/compressing/assets/57489136/8299810a-98aa-46cf-9750-6d83394f9ba4)

**Comment by fengmk2** [comment]
> > 有人可以提供一个有问题的 zip 测试文件么，这样我可以作为测试用例，尝试解决一下。
> 
> [configs.zip](https://github.com/node-modules/compressing/files/12414467/configs.zip) ![image](https://user-images.githubusercontent.com/57489136/262526179-8299810a-98aa-46cf-9750-6d83394f9ba4.png)

Thanks♪(･ω･)ﾉ

**Comment by fengmk2** [comment]
entry 缺少文件名字符编码的信息，无法做到完全自动化解决。只能由用户传入指定文件编码参数了。

**Comment by hezhongfeng** [comment]
好的，谢谢解答。
