### ISSUE TITLE
每次压缩文件夹，得到 zip 文件的 md5 都不一样

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [node-modules/compressing#30]
如题，怎么解决？？？

**Comment by fengmk2** [comment]
zip 文件有元信息，相同文件夹得到的压缩文件肯定不一样。你可以使用普通的 zip 工具压缩再计算 md5 试试。

**Comment by Mr-jiangzhiguo** [comment]
> zip 文件有元信息，相同文件夹得到的压缩文件肯定不一样。你可以使用普通的 zip 工具压缩再计算 md5 试试。

好的大佬，我用tar命令试试

**Comment by Mr-jiangzhiguo** [comment]
同一文件的两次 zip 内容不一致: [https://adoyle.me/blog/why-zip-file-checksum-changed.html](https://adoyle.me/blog/why-zip-file-checksum-changed.html)
