### ISSUE TITLE
windows 7 系统中打包的tgz包,解压到linux以后,无正确的目录结构

### ISSUE THREAD

**Issue by changchengqin** [node-modules/compressing#33]
windows 下打包以后,压缩包中出现了很多PaxHeader文件.
![image](https://user-images.githubusercontent.com/3336443/66554260-4014f500-eb7f-11e9-8150-6394eee40dd0.png)

在Ubuntu 16.04中解压以后，文件目录结构是平的
![image](https://user-images.githubusercontent.com/3336443/66554663-f8429d80-eb7f-11e9-981b-b917eb40b968.png)

**Comment by CIGE-Vince** [comment]
因为里面有个path.join()的问题，要改成path.posix.join()
