### ISSUE TITLE
压缩文件后的顶层目录

### ISSUE THREAD

**Issue by weijiafu14** [node-modules/compressing#52]
可以压缩文件时得到的压缩文件后没有顶层目录么，就是说我addEntry 加入多少个文件解压出来就是这些，我现在用每次都有一个顶层目录

**Comment by LouisaNikita** [comment]
> 可以压缩文件时得到的压缩文件后没有顶层目录么，就是说我addEntry 加入多少个文件解压出来就是这些，我现在用每次都有一个顶层目录

+1

**Comment by a90120411** [comment]
参数设置 `{ ignoreBase: true }`

**Comment by leno23** [comment]
> 参数设置 `{ ignoreBase: true }`

牛蛙

**Comment by LouisaNikita** [comment]
我已收到你的邮件，谢谢！

**Comment by LouisaNikita** [comment]
我已收到你的邮件，谢谢！
