### ISSUE TITLE
Bug: Cannot uncompress link file

### ISSUE THREAD

**Issue by inlann** [node-modules/compressing#66]
hello:

When I used compressing a tar.gz file by running `compressing.tgz.uncompress('./test.tar.gz', 'bin');`, It uncompressed the soft link files in the tar.gz package as a folder (the `idle3`):

```lang=shell
mac@Titan bin % ls -al       
drwxr-xr-x   2 mac  staff        64 Jan 25 16:30 idle3
-rwxr-xr-x   1 mac  staff       117 Jan 25 16:30 idle3.9
```

But actually it's a link file:

```lang=shell
mac@Titan bin % ls -al
lrwxr-xr-x  1 mac  staff    7 Oct 12 16:49 idle3 -> idle3.9
-rwxr-xr-x  1 mac  staff  117 Oct 12 16:49 idle3.9
```

**Comment by fengmk2** [comment]
https://github.com/node-modules/compressing/pull/31
