### ISSUE TITLE
pipe is not defined

### ISSUE THREAD

**Issue by zhuwei12** [node-modules/compressing#67]
![image](https://user-images.githubusercontent.com/25732723/152762956-c3ff153f-e62d-4dca-9213-0420605e2ab9.png)
what is this pipe for? why use pipe without defining it?

**Comment by fengmk2** [comment]
[pump](https://www.npmjs.com/package/pump) or [stream.pipeline](https://nodejs.org/dist/latest-v16.x/docs/api/stream.html#streampipelinesource-transforms-destination-callback)
