### ISSUE TITLE
is it possible to zip a directory without including the parent directory as root?

### ISSUE THREAD

**Issue by jhudson8** [node-modules/compressing#8]
for example `compressing.zip.compressDir('/foo/bar', 'foo.zip')`
will end up with 
```
/bar/a.txt
/bar/b.txt
```
whereas I'd like to have
```
/a.txt
/b.txt
```

Thanks

**Comment by wiliam-paradox** [comment]
I think that at the time of writing this, it's resolved. I have seen in the code the next:

As third argument, pass `ignoreBase` as true.

```
compressing.zip.compressDir('/foo/bar/', 'foo.zip', {
    ignoreBase: true
});
```

**Comment by davidkhala** [comment]
It should be add to document, definitely
