### ISSUE TITLE
Buffer() is deprecated due to security and usability issues. in fd-slicer use.

### ISSUE THREAD

**Issue by handyzhang** [node-modules/compressing#84]
- compressing v1.7.0
- yauzl  v2.10.0
- fd-slicer v1.1.0
- node v16.15.1

<img width="957" alt="image" src="https://user-images.githubusercontent.com/32894109/220276343-d6269d11-4694-4bcf-927b-3532e5fd3b8a.png">

**Comment by handyzhang** [comment]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/32894109/220276840-46f6caa6-0e38-4fcf-9d40-8f862612abf7.png">

**Comment by fengmk2** [comment]
fs-slicer 不是 compressing 依赖的

**Comment by fengmk2** [comment]
https://npmmirror.com/package/fs-slicer

**Comment by handyzhang** [comment]
@fengmk2  如图compressing依赖yauzl，而yauzl依赖fs-slicer 
<img width="643" alt="image" src="https://user-images.githubusercontent.com/32894109/220293949-73a4c0fd-8fd7-4420-a77e-dd167d46e671.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/32894109/220294100-93b29c19-3f2b-4595-afd1-1f989d688f6d.png">

compressing v1.7.0
↓
yauzl v2.10.0
↓
fd-slicer v1.1.0

**Comment by handyzhang** [comment]
@fengmk2 抱歉 应该是fs-slicer

compressing依赖yauzl
yauzl依赖了fs-slicer

**Comment by handyzhang** [comment]
@fengmk2  抱歉，应该是 fd-slicer插件，是存在依赖关系的

compressing v1.7.0
↓
yauzl v2.10.0
↓
fd-slicer v1.1.0

**Comment by fengmk2** [comment]
https://github.com/andrewrk/node-fd-slicer/pull/2

**Comment by fengmk2** [comment]
https://github.com/thejoshwolfe/yauzl/pull/115

**Comment by fengmk2** [comment]
fork 一份 https://github.com/node-modules/yauzl 来维护

**Comment by fengmk2** [comment]
@handyzhang 可以安装最新版本试试。
