### ISSUE TITLE
怎么获取解压后的文件夹和文件列表

### ISSUE THREAD

**Issue by lecykx** [node-modules/compressing#87]
您好，请问怎么获取解压后的文件夹和文件列表？我看了一下历史旧的版本支持，新的版本好像又去掉了

**Comment by fengmk2** [comment]
解压出来就是普通的文件目录了，使用 fs 模块读取即可。

**Comment by lecykx** [comment]
确实可以通过fs自己来读取，只是想着竟然有返回就应该考虑一下应用的场景
