### ISSUE TITLE
tgz.uncompress shortcut file link not work

### ISSUE THREAD

**Issue by allenlongbaobao** [node-modules/compressing#93]
as title said, i use `compressing.tgz.uncompress(tarPath, targetPath)` to uncompress a tar.gz file

after that, i found the pnpm node_modules shortcut folder not work like that
![image](https://github.com/node-modules/compressing/assets/3255868/1a68735b-5e7c-4313-a51b-86c391961d01)

what i expect after uncompress is like this:
![image](https://github.com/node-modules/compressing/assets/3255868/f5fa55ac-37f4-413d-89a3-615d2aeaa807)

**Comment by fengmk2** [comment]
Can you provide a reproducible code repository?

**Comment by fengmk2** [comment]
https://github.com/node-modules/compressing/pull/31
