### ISSUE TITLE
tar包在window压缩时入口路劲分隔符错误导致linux无法正确解压出包内目录结构

### ISSUE THREAD

**Issue by wghule** [node-modules/compressing#94]
tar包在window压缩时入口路劲在_addDirEntry处理 newOpts.relativePath 应该固定以linux的分隔符 / 来组织路径，以兼容window和linux的tar包解压

**Comment by fengmk2** [comment]
@wghule 欢迎来贡献解决

**Comment by fengmk2** [comment]
https://github.com/node-modules/compressing/pull/106
